# -----------------------------------------------------------------------------
# Frontend Deployment
#
# Deploys the React frontend application.
# Kubernetes pulls the Docker image from Amazon ECR.
# -----------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment

metadata:
  name: maintenance-frontend
  labels:
    app: maintenance-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: maintenance-frontend

  template:
    metadata:
      labels:
        app: maintenance-frontend

    spec:
      containers:
        - name: maintenance-frontend

          image: ${FRONTEND_IMAGE}

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: VITE_API_BASE_URL
              value: http://a1b898229bb394145824f3bbc764a014-1160686867.us-east-1.elb.amazonaws.com